PROJECT_NAME=hello_world
DOCKER_REPO=${PROJECT_NAME}
DOCKER_VERSION=0.00.01
DOCKER_HUB_USER=jakeinit

DOCKER_FILE=DockerfileDevEnv
#DOCKER_FILE=DockerfileProdEnv
#DOCKER_VOLUME_NAME=logsVolume
DOCKER_VOLUME_NAME=helloWorldVolume

DOCKER_CC=gcc
DOCKER_CXX=g++
DOCKER_SHELL=bash
DOCKER_IMAGE_BUILD_FLAGS=--no-cache=true

DOCKER_SYS_ARCH=linux/amd64
#DOCKER_SYS_ARCH=linux/arm64

HOST_MOUNT_PATH=${CURDIR}
DOCKER_SOURCE_PATH=/${PROJECT_NAME}
DOCKER_BUILD_DIR=build

CONTAINER_VOLUME_PATH=logs

include buildtools/Makefile
